// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA57oL9Awp0_dExLZJLlOOLXHMDmrChA-4',
    appId: '1:1045964229167:web:5bac994cf7a8fcad7b94da',
    messagingSenderId: '1045964229167',
    projectId: 'mooha-aa395',
    authDomain: 'mooha-aa395.firebaseapp.com',
    storageBucket: 'mooha-aa395.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYM9v_GkIuL2ftIjvk2zid0YLssOO4FYc',
    appId: '1:1045964229167:android:50ed224dd42e18697b94da',
    messagingSenderId: '1045964229167',
    projectId: 'mooha-aa395',
    storageBucket: 'mooha-aa395.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAv7HTvWUKI46T8O8p8fzXfHxm3z2lyq8',
    appId: '1:1045964229167:ios:53fbe1743751d8e87b94da',
    messagingSenderId: '1045964229167',
    projectId: 'mooha-aa395',
    storageBucket: 'mooha-aa395.appspot.com',
    iosClientId: '1045964229167-kv33uao951a371o5tu4i6mqvr9ousa8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.mooha',
  );
}
